### ISSUE TITLE
Could not to connect socket xx.xx.xx.xx:49285 - No connection could be made because the target machine actively refused it xx.xx.xx.xx:49285

### ISSUE THREAD

**Issue by radduri** [sparkeh9/CoreFTP#17]
Can you please help me on the below error

_Error: Could not to connect socket xx.xx.xx.xx:49285 - No connection could be made because the target machine actively refused it xx.xx.xx.xx:49285_

The below is the logic which i have written

                string logData = JsonConvert.SerializeObject(log);
                _logger.LogInformation(logData);
                byte[] byteArray = Encoding.ASCII.GetBytes(logData);
                MemoryStream stream = new MemoryStream(byteArray);
                var configuration = new FtpClientConfiguration
                {
                    IgnoreCertificateErrors = true,
                    Host = _host,
                    //Port = _port,
                    BaseDirectory = _path,
                    EncryptionType = FtpEncryption.Implicit
                };

                if (!string.IsNullOrEmpty(_username))
                {
                    configuration.Username = _username;
                    configuration.Password = _password;
                }

                using (var ftpClient = new FtpClient(configuration))
                {
                    ftpClient.Logger = _logger;
                    _logger.LogInformation("Trying to login");
                    await ftpClient.LoginAsync();
                    _logger.LogInformation("Logged in");
                    using (var writeStream = await ftpClient.OpenFileWriteStreamAsync($"CS-{String.Format("{0:s}", DateTime.Now).Replace(':', '-')}.json"))
                    {
                        _logger.LogInformation("Trying to Writing in");
                        await stream.CopyToAsync(writeStream);
                        _logger.LogInformation("Write successfully");
                    }
                }

**Comment by radduri** [comment]
The below is the full stack trace 

AuditLogMiddleware
No connection could be made because the target machine actively refused it 10.27.5.99:50444

System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: No connection could be made because the target machine actively refused it 10.27.5.99:50444
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at CoreFtp.Infrastructure.Stream.FtpControlStream.<ConnectSocketAsync>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CoreFtp.Infrastructure.Stream.FtpControlStream.<ConnectStreamAsync>d__60.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CoreFtp.Infrastructure.Stream.FtpControlStream.<OpenDataStreamAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CoreFtp.FtpClient.<ConnectDataStreamAsync>d__56.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CoreFtp.FtpClient.<OpenFileStreamAsync>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CoreFtp.FtpClient.<OpenFileWriteStreamAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AuditLogMiddleware.<LogAuditInformation>d__10.MoveNext() in D:\BuildAgent\work\db71b717f2c508ca\src\AuditLogMiddleware.cs:line 117

**Comment by sparkeh9** [comment]
You have an FTP server running on 10.27.5.99, and have passive mode enabled and working in another client?
