### ISSUE TITLE
System.AggregateException

### ISSUE THREAD

**Issue by Immortal-** [sparkeh9/CoreFTP#39]
`Unhandled Exception: System.AggregateException: One or more errors occurred. (Syntax error, command unrecognized.) ---> CoreFtp.I
nfrastructure.FtpException: Syntax error, command unrecognized.
   at CoreFtp.FtpClient.<ConnectDataStreamAsync>d__56.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CoreFtp.FtpClient.<OpenFileStreamAsync>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CoreFtp.FtpClient.<OpenFileReadStreamAsync>d__42.MoveNext()
   --- End of inner exception stack trace ---
`

Got this by logging into a steam game server via ftp and grabbing all the files and throwing into a log class which has 
    ` string Name { get; set; }
        long Size { get; set; }
        string Body { get; set; }
        DateTime LastEdit { get; set; }`
the body is made by using a text reader on OpenFileReadStreamAsync

What I got before the error fired was correct.

`
FileSize: 44393 Name: l064_094_095_098_27025_201802240203_002.log Date: 4/9/2018 11:14:00 PM
FileSize: 41393 Name: l064_094_095_098_27025_201802252348_002.log Date: 4/9/2018 11:14:00 PM
FileSize: 47973 Name: l064_094_095_098_27025_201802260042_002.log Date: 4/9/2018 11:14:00 PM
FileSize: 39888 Name: l064_094_095_098_27025_201802270105_002.log Date: 4/9/2018 11:14:00 PM
FileSize: 58090 Name: l064_094_095_098_27025_201803030110_002.log Date: 4/9/2018 11:14:00 PM
FileSize: 49523 Name: l064_094_095_098_27025_201803090133_002.log Date: 4/9/2018 11:14:00 PM
FileSize: 1183 Name: l064_094_095_098_27025_201804091624_002.log Date: 4/10/2018 1:09:00 AM
FileSize: 1183 Name: l064_094_095_098_27025_201804092009_002.log Date: 4/10/2018 5:00:00 AM
FileSize: 1183 Name: l064_094_095_098_27025_201804100000_002.log Date: 4/10/2018 8:49:00 AM
FileSize: 1183 Name: l064_094_095_098_27025_201804100349_002.log Date: 4/10/2018 12:34:00 PM
FileSize: 1183 Name: l064_094_095_098_27025_201804100734_002.log Date: 4/10/2018 4:18:00 PM
FileSize: 1183 Name: l064_094_095_098_27025_201804101118_002.log Date: 4/10/2018 8:02:00 PM

`

**Comment by sparkeh9** [comment]
Closing this as a configuration/environment issue. The `System.AggregateException` wrapping `AuthenticationException: The remote certificate is invalid according to the validation procedure` indicates that the FTP server's SSL/TLS certificate is not trusted by the client machine's certificate store (e.g. self-signed, expired, or hostname mismatch).

**Solutions available in v2.1.0:**
1. Set `IgnoreCertificateErrors = true` to bypass all certificate validation (not recommended for production).
2. Use the new `ServerCertificateValidationCallback` to selectively trust specific certificates:

```csharp
var ftpClient = new FtpClient(new FtpClientConfiguration
{
    Host = "your-server.com",
    EncryptionType = FtpEncryption.Implicit,
    IgnoreCertificateErrors = false,
    ServerCertificateValidationCallback = (cert, chain, errors) =>
    {
        return cert.GetCertHashString() == "YOUR_THUMBPRINT";
    }
});
```

If you continue to experience issues, please ensure your server's certificate chain is valid and that the hostname matches the certificate's CN/SAN.
